spring:
  application:
    name: developer-notes
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: wordpass1
    platform: org.hibernate.dialect.PostgreSQLDialect
    initialization-mode: always
    dbcp2:
      default-auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

server:
  port: 8080
