spring:
  application:
    name: developer-notes
  datasource:
    url: jdbc:postgresql://localhost:54842/
    username: postgres
    password: wordpass1
    platform: postgres

server:
  port: 8080

hibernate:
  show_sql: true

datasource:
  url:
  username:
  password: